# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20110423113825) do

  create_table "categories", :force => true do |t|
    t.integer  "super_category_id"
    t.string   "code"
    t.string   "name"
    t.boolean  "enabled"
    t.boolean  "visible"
    t.boolean  "enhanced"
    t.date     "new_from"
    t.date     "new_to"
    t.string   "friendly_url"
    t.string   "css_class"
    t.string   "title"
    t.integer  "home_order"
    t.string   "home_title"
    t.string   "home_text"
    t.string   "home_link"
    t.string   "home_image_src"
    t.integer  "list_order"
    t.string   "list_title"
    t.string   "list_text"
    t.string   "list_link"
    t.string   "list_image_src"
    t.integer  "category_order"
    t.string   "category_title"
    t.string   "category_text"
    t.string   "category_link"
    t.string   "category_image_src"
    t.integer  "enhanced_order"
    t.string   "enhanced_title"
    t.string   "enhanced_text"
    t.string   "enhanced_link"
    t.string   "enhanced_image_src"
    t.string   "recommended_title"
    t.string   "recommended_text"
    t.string   "recommended_link"
    t.string   "recommended_image_src"
    t.string   "detail_title"
    t.text     "detail_text"
    t.string   "detail_link"
    t.string   "secondary_detail_title"
    t.text     "secondary_detail_text"
    t.string   "secondary_detail_link"
    t.string   "detail_image_src"
    t.string   "meta_title"
    t.string   "meta_description"
    t.string   "meta_keywords"
    t.string   "other_metas"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "categories_products", :id => false, :force => true do |t|
    t.integer "category_id"
    t.integer "product_id"
  end

  create_table "products", :force => true do |t|
    t.integer  "category_id"
    t.string   "product_type"
    t.string   "code"
    t.string   "name"
    t.boolean  "enabled"
    t.boolean  "visible"
    t.boolean  "saleable"
    t.boolean  "enhanced"
    t.date     "new_from"
    t.date     "new_to"
    t.decimal  "cost"
    t.integer  "iva"
    t.decimal  "shipping_cost"
    t.decimal  "price"
    t.decimal  "special_price"
    t.date     "special_price_from"
    t.date     "special_price_to"
    t.decimal  "width"
    t.decimal  "height"
    t.decimal  "deep"
    t.decimal  "weight"
    t.string   "warehouse_location"
    t.boolean  "manage_stock"
    t.integer  "stock_quantity"
    t.boolean  "stock_availability"
    t.string   "friendly_url"
    t.string   "meta_title"
    t.string   "meta_description"
    t.string   "meta_keywords"
    t.string   "other_metas"
    t.string   "css_class"
    t.string   "title"
    t.integer  "home_order"
    t.string   "home_title"
    t.string   "home_text"
    t.string   "home_link"
    t.string   "home_image_src"
    t.integer  "list_order"
    t.string   "list_title"
    t.string   "list_text"
    t.string   "list_link"
    t.string   "list_image_src"
    t.integer  "category_order"
    t.string   "category_title"
    t.string   "category_text"
    t.string   "category_link"
    t.string   "category_image_src"
    t.string   "cart_title"
    t.string   "cart_text"
    t.string   "cart_link"
    t.string   "cart_image_src"
    t.integer  "enhanced_order"
    t.string   "enhanced_title"
    t.string   "enhanced_text"
    t.string   "enhanced_link"
    t.string   "enhanced_image_src"
    t.string   "recommended_title"
    t.string   "recommended_text"
    t.string   "recommended_link"
    t.string   "recommended_image_src"
    t.string   "detail_title"
    t.text     "detail_text"
    t.string   "detail_link"
    t.string   "secondary_detail_title"
    t.text     "secondary_detail_text"
    t.string   "secondary_detail_link"
    t.string   "detail_image_src"
    t.string   "detail_image2_src"
    t.string   "detail_image3_src"
    t.string   "detail_image4_src"
    t.string   "detail_image5_src"
    t.string   "detail_image6_src"
    t.integer  "sales_quantity"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
